const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'Shirts',
      slug: 'free-shirt',
      image: '/images/shirt1.jpg',
      price: 400,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'fit-shirt',
      slug: 'free-shirt',
      image: '/images/shirt2.jpg',
      price: 500,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 13,
      countInStock: 23,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      category: 'Shirts',
      slug: 'slim-shirt',
      image: '/images/shirt3.jpg',
      price: 700,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Goalf Pants',
      category: 'pants',
      slug: 'goalf-pants',
      image: '/images/pants1.jpg',
      price: 450,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      category: 'Pants',
      slug: 'fit-pants',
      image: '/images/pants2.jpg',
      price: 400,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      category: 'Pants',
      slug: 'classic-pants',
      image: '/images/pants3.jpg',
      price: 400,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;
